### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

# Tensor 


*   could be scalar, vector, matrix, or multi-dimensional arrays
* tensor arithmetic operation: `+-*/` or `torch.add()`, `torch.sub()`, `torch.mul()`, `torch.div()`
*  matrix multiplication: `@` / `torch.mm()` / `torch.matmul()` / `matrix1.mm(matrix2)`
*   shape of a tensor: `tensor_variable.shape()`



### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [16]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [ ]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [ ]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - Stacking and spliting tensors
```
torch.vstack()/torch.vsplit()/torch.hsplit()/torch.hstack()
```


In [10]:
# Example 1 - torch.hstack()/torch.vstack() - Stack two tensors horizontally (h) or vertically (v)

#stacking 1 dimentional tensors
a = torch.tensor([1,2,3])
b = torch.tensor([7,8,9])
hs1 = torch.hstack((a,b))
vs1 = torch.vstack((a,b))
print("horizontal 1-d stacking: \n{}\nvertical 1-d stacking: \n{}".format(hs1, vs1))

#stacking 2 dimentional tensors
c = torch.tensor([[1],[2],[3]])
d = torch.tensor([[7],[8],[9]])
hs2 = torch.hstack((c,d))
vs2 = torch.vstack((c,d))
print("horizontal 2-d stacking: \n{}\nvertical 2-d stacking: \n{}".format(hs2, vs2))

horizontal 1-d stacking: 
tensor([1, 2, 3, 7, 8, 9])
vertical 1-d stacking: 
tensor([[1, 2, 3],
        [7, 8, 9]])
horizontal 2-d stacking: 
tensor([[1, 7],
        [2, 8],
        [3, 9]])
vertical 2-d stacking: 
tensor([[1],
        [2],
        [3],
        [7],
        [8],
        [9]])


In [14]:
# Example 2 - torch.vsplit()/torch.hsplit() - Split a two or higher dimemtional tensor horizontally (h) or vertically (v)
t = torch.arange(36.0).reshape(6,6) 

h = torch.hsplit(t,3)
v = torch.vsplit(t,3)

print("original tensor\n{}\nvertically splitted tensor\n{}\nhorizontally splitted tensor\n{}".format(t, h, v))

original tensor
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]])
vertically splitted tensor
(tensor([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.],
        [24., 25.],
        [30., 31.]]), tensor([[ 2.,  3.],
        [ 8.,  9.],
        [14., 15.],
        [20., 21.],
        [26., 27.],
        [32., 33.]]), tensor([[ 4.,  5.],
        [10., 11.],
        [16., 17.],
        [22., 23.],
        [28., 29.],
        [34., 35.]]))
horizontally splitted tensor
(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]), tensor([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]), tensor([[24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]]))


### Function 2 - Generate a tensor with prefilled scalar value


```
zeros()/ones()/eyes()
```


In [21]:
# Example 1 - zeros()/ones() - generates a scalar of designated size filled with 0 or 1

zeros = torch.zeros(4,4)
ones = torch.ones(4,4)

print("zeros\n{}\nones\n{}".format(zero,ones))

zeros
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
# Example 2 - eyes() - generates a scaler of desired size, with the diagonals being all 1s

eye = torch.eye(5)

print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Function 3 - transpose and permute a tensor

```
torch.transpose()/torch.permute
```

In [42]:
# Example 1 - these two functions transpose or permute a tensor based on the dimension arguments that it is given

a = torch.tensor(np.random.randint(low=0, high=10, size=(4,4)))

trans = torch.Tensor.transpose(a, 0, 1)
perm = torch.Tensor.permute(a, (-1, 0))

print("original tensor\n{}\ntransposed tensor\n{}\npermuted tensor\n{}".format(a, trans, perm))

original tensor
tensor([[0, 8, 5, 6],
        [0, 6, 8, 8],
        [2, 2, 1, 7],
        [2, 4, 1, 8]])
transposed tensor
tensor([[0, 0, 2, 2],
        [8, 6, 2, 4],
        [5, 8, 1, 1],
        [6, 8, 7, 8]])
permuted tensor
tensor([[0, 0, 2, 2],
        [8, 6, 2, 4],
        [5, 8, 1, 1],
        [6, 8, 7, 8]])


### Function 4 - shrink or expand a tensor

```
torch.squeeze()/torch.unsqueeze()
```

In [52]:
# Example 1  
# squeeze() removes the tensor with only one dimension in a bigger tensor
# unsqueeze() adds a dimension of size one inserted at the specified position.

x = torch.ones(1,2,1,3,1,4,1,5)

y = torch.squeeze(x) # with an optional argument to designate the dimensions to be squeezed

z = torch.unsqueeze(x, 8) # the second arguments designates the dimensions at which the tensor will be expanded

print("original size: {}\nsqueezed size: {}\nunsqueezed size: {}".format(x.size(), y.size(), z.size()))



original size: torch.Size([1, 2, 1, 3, 1, 4, 1, 5])
squeezed size: torch.Size([2, 3, 4, 5])
unsqueezed size: torch.Size([1, 2, 1, 3, 1, 4, 1, 5, 1])


### Function 5

```
torch.reshape() / tensor.view()
```

In [78]:
# reshape() - reshapes a given tensor to designated dimensions
x = torch.arange(10)
y = torch.reshape(x, (5,2))

# view() - Returns a new tensor with the same data as the self tensor but of a different shape.
z = x.view((2,5))

print("original shape\n=>{}\nreshaped tensor\n=>{}\nview()\n=>{}".format(x, y, z))

original shape
=>tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped tensor
=>tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
view()
=>tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
